// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form: dynamic(() => import("./ContactForm")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  main: dynamic(() => import("./Main")),
  photo_gallery: dynamic(() => import("./PhotoGallery")),
  steps: dynamic(() => import("./Steps")),
  text_button: dynamic(() => import("./TextButton")),
  text_image: dynamic(() => import("./TextImage")),
  text_with_features: dynamic(() => import("./TextWithFeatures")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
