// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  main: dynamic(() => import("./Main")),
  text_with_features: dynamic(() => import("./TextWithFeatures")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
